fluid_dynamics_node:
  ros__parameters:
    # 基本参数
    urdf_path: "/home/wwl/ros2-pinocchio/install/pinocchio_ros2_example/share/pinocchio_ros2_example/models/two_link.urdf"
    free_flyer: false
    fluid_frames: ["link_1", "link_2"]

    # 流场（世界系）
    v_current_world: [0.03, 0.0, 0.0]
    rho: 1000.0

    # 通用几何/阻力系数
    default_area: 0.01
    default_cd_quad: 0.0
    default_cd_lin: 0.0
    default_cd_ang_lin: 0.1

    # link_1 参数（附加质量 + 线/非线性阻尼）
    link_1.m_u: 0.089
    link_1.m_v: 0.089
    link_1.m_r: 0.16
    link_1.d_lu: 0.4
    link_1.d_lv: 3.0
    link_1.d_lr: 0.0
    link_1.d_nu: 12.9
    link_1.d_nv: 21.3
    link_1.d_nr: 0.0

    # link_2 参数（如无特殊，可与 link_1 相同）
    link_2.m_u: 0.089
    link_2.m_v: 0.089
    link_2.m_r: 0.16
    link_2.d_lu: 0.4
    link_2.d_lv: 3.0
    link_2.d_lr: 0.0
    link_2.d_nu: 12.9
    link_2.d_nv: 21.3
    link_2.d_nr: 0.0


